export const PASSWORD_MIN_CHARACTER = 8;
export const PASSWORD_MAX_CHARACTER = 32;
export const FIRST_NAME_MAX_CHARACTER = 50;
export const FIRST_NAME_MIN_CHARACTER = 2;
export const LAST_NAME_MAX_CHARACTER = 50;
export const LAST_NAME_MIN_CHARACTER = 2;
export const MOBILE_NUMBER_MIN_CHARACTER = 8;
